#!/usr/bin/env python3
"""Bundle the Alloy CSS source tree into a single file.

Reads ``zensical_alloy/.../main.css`` and recursively inlines each
``@import`` target, stripping any ``?v=...`` cache-bust query. The output is
written to ``main.bundle.css`` next to it. ``main.html`` references the
bundle at runtime so the browser fetches a single stylesheet instead of
chasing a 23-deep ``@import`` chain.

Usage:

    python scripts/bundle-css.py            # one-shot bundle
    python scripts/bundle-css.py --watch    # poll sources and re-bundle
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path


IMPORT_RE = re.compile(r'@import\s+url\("([^"?]+)(?:\?[^"]*)?"\);\s*\n?')

ROOT = Path(__file__).resolve().parents[1]
STYLES_DIR = ROOT / "zensical_alloy" / "assets" / "stylesheets" / "zensical-alloy"
ENTRY = STYLES_DIR / "main.css"
OUTPUT = STYLES_DIR / "main.bundle.css"
HEADER = (
    "/* Auto-generated by scripts/bundle-css.py. Do not edit by hand - edit\n"
    " * main.css and its @import children, then re-run the bundler. */\n\n"
)


def inline(text: str, base: Path) -> str:
    """Resolve @import statements in *text*, returning fully-inlined CSS."""
    def replace(match: re.Match[str]) -> str:
        rel = match.group(1)
        target = (base / rel).resolve()
        if not target.exists():
            raise FileNotFoundError(f"Import target not found: {target}")
        return inline(target.read_text(encoding="utf-8"), target.parent)
    return IMPORT_RE.sub(replace, text)


def bundle() -> Path:
    """Generate main.bundle.css from main.css and its imports."""
    bundled = inline(ENTRY.read_text(encoding="utf-8"), ENTRY.parent)
    OUTPUT.write_text(HEADER + bundled, encoding="utf-8")
    return OUTPUT


def collect_sources() -> list[Path]:
    """Walk the @import graph and return every CSS file that feeds the bundle."""
    seen: set[Path] = set()

    def walk(path: Path) -> None:
        path = path.resolve()
        if path in seen:
            return
        seen.add(path)
        for match in IMPORT_RE.finditer(path.read_text(encoding="utf-8")):
            child = (path.parent / match.group(1)).resolve()
            if child.exists():
                walk(child)

    walk(ENTRY)
    return sorted(seen)


def watch(interval: float) -> None:
    """Re-bundle whenever any source file's mtime changes."""
    sources = collect_sources()
    mtimes = {path: path.stat().st_mtime for path in sources}
    bundle()
    print(f"Bundled {len(sources)} files -> {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
    try:
        while True:
            time.sleep(interval)
            changed = []
            # Re-discover sources on each pass in case @imports were edited.
            current = collect_sources()
            for path in current:
                m = path.stat().st_mtime
                if m != mtimes.get(path):
                    changed.append(path)
                    mtimes[path] = m
            for stale in set(mtimes) - set(current):
                mtimes.pop(stale, None)
            if changed:
                bundle()
                names = ", ".join(p.name for p in changed)
                print(f"Re-bundled after change to {names}", file=sys.stderr)
    except KeyboardInterrupt:
        return


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Watch source files and re-bundle on change.",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=0.5,
        help="Poll interval (seconds) for --watch mode.",
    )
    args = parser.parse_args()

    if args.watch:
        watch(args.interval)
    else:
        path = bundle()
        print(f"Wrote {path.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
